driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
  - name: debian-8.4
  - name: fedora-23
  - name: opensuse-13.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[route53_test::default]
    attributes:
      route53:
        zone_id: <%= ENV['AWS_ZONE_ID'] || 'Z2DEMODEMODEMO' %>
        aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        aws_region: <%= ENV['AWS_REGION'] %>
      records:
        generic_record:
          name: 'kitchen-test.yourdomain.org'
          value: '16.8.4.3'
          type: 'A'
          ttl: 3600
        alias_record:
          name: 'kitchen-test-alias.yourdomain.org'
          alias_target:
            dns_name: 'dns-name'
            hosted_zone_id: 'host-zone-id'
            evaluate_target_health: false
          type: 'A'
          run: true
